[package]
name = "nom_cbor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
ciborium = "0.2.0"
either = "1.8.1"
nom = "7.1.3"
num-traits = "0.2.15"
thiserror = "1.0.38"
