[package]
name = "cuddle"
version = "0.1.0"
edition = "2021"
description = "A library to parse and validate CDDL and CBOR."
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
