[package]
name = "cyborg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = "0.2.0"
nom = "7.1.3"
nom_cbor = { path = "../nom-cbor", version = "0.1.0" }
thiserror = "1.0.38"
